name: Node.js continuous integration

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [6.7.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
          envkey_VITE_API_ROUTE: ${{ secrets.VITE_API_ROUTE }}
          envkey_VITE_API_URL: ${{ secrets.VITE_API_URL }}
          file_name: .env
      - name: Install dependencies
        run: |
          npm install -g pnpm@${{ matrix.pnpm-version }}
          pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
